worker_processes auto;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    /dev/stdout;
    sendfile      on;
    keepalive_timeout 65;

    # vhosts extras (vazio desde 16/08/2026, quando o site saiu do bundle)
    include /etc/nginx/sites-enabled/*.conf;

    # Edge :8080
    include /etc/nginx/edge.conf;
}
